# =======================================================
#  Render Blueprint
# =======================================================

services:
  # ─────────── API (web) ───────────
  - name: api-fastapi
    type: web
    runtime: docker
    dockerfilePath: services/api-fastapi/Dockerfile
    plan: starter
    envVars:
      - key: STRIPE_SECRET         ; sync: false
      - key: STRIPE_PRICE_ID       ; sync: false
      - key: STRIPE_WEBHOOK_SECRET ; sync: false
      - key: SUCCESS_URL           ; sync: false
      - key: CANCEL_URL            ; sync: false
      - key: REDIS_URL
        fromDatabase:
          name: redis
          property: connectionString

  # ─────────── WORKER (RQ) ───────────
  - name: scan-runner
    type: worker
    runtime: docker
    dockerfilePath: workers/scan-runner/Dockerfile
    plan: starter
    envVars:
      - key: REDIS_URL
        fromDatabase:
          name: redis
          property: connectionString

# -------------------------------------------------------
#  Bases de datos
# -------------------------------------------------------
databases:
  # Redis 7 – Starter (512 MB)
  - name: redis
    type: redis
    plan: starter
    ipAllowList: []          # vacío = solo accesible dentro de Render VPC
