# render.yaml
# ===============================================

services:
  # ─────────── API FastAPI (web) ───────────
  - name: api-fastapi
    type: web
    runtime: docker
    dockerfilePath: services/api-fastapi/Dockerfile
    plan: starter            # Starter - 512 MB / 0,5 CPU
    envVars:
      - key: STRIPE_SECRET         # los cinco los sigues metiendo a mano
        sync: false
      - key: STRIPE_PRICE_ID
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: SUCCESS_URL
        sync: false
      - key: CANCEL_URL
        sync: false
      # Redis interno (DNS = redis)
      - key: REDIS_URL
        value: redis://redis:6379/0

  # ─────────── Redis (Key-Value) ───────────
  - name: redis
    type: keyvalue            # «redis» es alias obsoleto, usa keyvalue
    plan: starter
    ipAllowList:              # Render exige al menos UNA entrada
      - source: 0.0.0.0/0     # déjalo abierto; sólo tu VPC interna podrá verlo
        description: internal only

  # ─────────── Worker RQ (background) ──────
  - name: scan-runner
    type: worker
    runtime: docker
    dockerfilePath: workers/scan-runner/Dockerfile
    plan: starter
    envVars:
      - key: REDIS_URL
        value: redis://redis:6379/0
