services:
# ──────── API (web) ────────
# ─────────── API ───────────
- name: api-fastapi
  type: web
  runtime: docker
  dockerfilePath: services/api-fastapi/Dockerfile
  plan: starter
  envVars:
    - key: STRIPE_SECRET
      sync: false
    - key: STRIPE_PRICE_ID
      sync: false
    - key: STRIPE_WEBHOOK_SECRET
      sync: false
    - key: SUCCESS_URL
      sync: false
    - key: CANCEL_URL
      sync: false
    - key: REDIS_URL
      value: redis://redis:6379/0          # URL interna
      
# ─────────── REDIS (DB) ──────────
- name: redis
  type: redis
  plan: starter
  ipAllowList: []                # ← requerido (lista vacía = solo interno)

# ─────────── WORKER RQ ───────────
- name: scan-runner
  type: worker
  runtime: docker
  dockerfilePath: workers/scan-runner/Dockerfile
  plan: starter
  envVars:
    - key: REDIS_URL
      fromDatabase:
        name: redis
        property: connectionString