# render.yaml
# ===============================================

services:
  # ─────────── API FastAPI (web) ───────────
  - name: api-fastapi
    type: web
    runtime: docker
    dockerfilePath: services/api-fastapi/Dockerfile
    dockerContext: services/api-fastapi
    plan: starter            # Starter - 512 MB / 0,5 CPU
    envVars:
      - key: STRIPE_SECRET         # los cinco los sigues metiendo a mano
        sync: false
      - key: STRIPE_PRICE_ID
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: SUCCESS_URL
        sync: false
      - key: CANCEL_URL
        sync: false
      # Redis interno (DNS = redis)
      - key: REDIS_URL
        value: redis://red-d1r7117diees73flo1lg:6379

  # ─────────── Redis (Key-Value) ───────────
  - name: redis
    type: keyvalue            # «redis» es alias obsoleto, usa keyvalue
    plan: starter
    ipAllowList:              # Render exige al menos UNA entrada
      - source: 0.0.0.0/0     # déjalo abierto; sólo tu VPC interna podrá verlo
        description: internal only

  # ─────────── Worker RQ (background) ──────
  - name: scan-runner
    type: worker
    runtime: docker
    dockerfilePath: Dockerfile.scan-runner
    dockerContext: .
    plan: standard    # Cambiado a standard para más recursos (1GB RAM / 1 CPU)
    envVars:
      - key: REDIS_URL
        value: redis://red-d1r7117diees73flo1lg:6379
      - key: MAILERSEND_API_KEY
        sync: false    # Configurar en el dashboard de Render
      - key: FROM_EMAIL
        value: informes@auditatetumiesmo.es
