# render.yaml
# ===============================================

services:
  # ─────────── Redis (Key-Value) ───────────
  - name: redis
    type: redis  # Use 'redis' instead of 'keyvalue' for better compatibility
    plan: starter
    ipAllowList:
      - source: 0.0.0.0/0
        description: internal only

  # ─────────── API FastAPI (web) ───────────
  - name: api-fastapi
    type: web
    runtime: docker
    dockerfilePath: services/api-fastapi/Dockerfile
    dockerContext: services/api-fastapi
    plan: starter            # Starter - 512 MB / 0,5 CPU
    envVars:
      - key: STRIPE_SECRET
        sync: false
      - key: STRIPE_PRICE_ID
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: SUCCESS_URL
        sync: false
      - key: CANCEL_URL
        sync: false
      # Use Render's internal service discovery for Redis
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString

  # ─────────── Worker RQ (background) ──────
  - name: scan-runner
    type: worker
    runtime: docker
    dockerfilePath: Dockerfile.scan-runner
    dockerContext: .
    plan: standard    # Standard for more resources (1GB RAM / 1 CPU)
    # Removed cap_add as it's not supported in Render worker services
    envVars:
      # Use Render's internal service discovery for Redis
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
      - key: MAILERSEND_API_KEY
        sync: false    # Configure in Render dashboard
      - key: FROM_EMAIL
        value: informes@auditatetumismo.es