# Configuración del Sistema Mejorado de Detección de Tecnologías
# =============================================================

# Configuración General
general:
  enable_enhanced_detection: true
  enable_legacy_fallback: true
  enable_parallel_detection: true
  enable_security_analysis: true
  enable_metrics: true
  validate_tools_on_startup: true
  debug_mode: false

# Configuración de Cache
cache:
  enabled: true
  ttl: 3600  # Time to live en segundos (1 hora)
  max_size: 1000  # Máximo número de entradas en cache
  redis_enabled: false
  redis_host: "localhost"
  redis_port: 6379
  redis_db: 0

# Configuración de Rendimiento
performance:
  max_workers: 4
  timeout: 30
  request_timeout: 15
  max_retries: 3
  retry_delay: 1
  rate_limit_enabled: true
  requests_per_minute: 60

# Configuración de Confianza
confidence:
  threshold: 0.7
  min_confidence: 0.3
  weight_wappalyzer: 0.4
  weight_whatweb: 0.3
  weight_httpx: 0.2
  weight_builtin: 0.1

# Configuración de Herramientas Externas
external_tools:
  wappalyzer:
    enabled: true
    command: "wappalyzer"
    timeout: 20
    max_retries: 2
    fallback_enabled: true
  
  whatweb:
    enabled: true
    command: "whatweb"
    timeout: 25
    max_retries: 2
    options: ["--quiet", "--no-errors"]
    fallback_enabled: true
  
  httpx:
    enabled: true
    command: "httpx"
    timeout: 15
    max_retries: 2
    options: ["-silent", "-json"]
    fallback_enabled: true
  
  curl:
    enabled: true
    command: "curl"
    timeout: 10
    options: ["-s", "-L", "--max-time", "10"]
    fallback_enabled: true

# Configuración de Análisis de Seguridad
security_analysis:
  enabled: true
  check_headers: true
  check_versions: true
  check_vulnerabilities: true
  vulnerability_sources:
    - "cve"
    - "exploit-db"
    - "security-advisories"
  
  # Cabeceras de seguridad a verificar
  security_headers:
    - "Content-Security-Policy"
    - "X-Frame-Options"
    - "X-Content-Type-Options"
    - "Strict-Transport-Security"
    - "X-XSS-Protection"
    - "Referrer-Policy"
    - "Permissions-Policy"
  
  # Configuración de riesgo
  risk_scoring:
    high_risk_technologies:
      - "WordPress"
      - "Drupal"
      - "Joomla"
    medium_risk_technologies:
      - "Apache"
      - "Nginx"
      - "PHP"
    low_risk_technologies:
      - "jQuery"
      - "Bootstrap"

# Configuración de Métricas
metrics:
  enabled: true
  export_enabled: true
  export_interval: 3600  # Exportar cada hora
  export_format: "json"
  export_path: "./metrics/"
  
  # Métricas a recopilar
  collect_performance: true
  collect_accuracy: true
  collect_tool_usage: true
  collect_errors: true
  
  # Retención de datos
  retention_days: 30
  max_records: 10000

# Configuración de Logging
logging:
  level: "INFO"
  format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
  file_enabled: true
  file_path: "./logs/enhanced_detection.log"
  max_file_size: "10MB"
  backup_count: 5
  console_enabled: true

# Configuración de Reportes
reporting:
  enabled: true
  format: "json"  # json, yaml, html
  include_raw_data: false
  include_metrics: true
  include_recommendations: true
  include_security_analysis: true
  
  # Configuración de reportes HTML
  html_template: "default"
  include_charts: true
  include_timeline: true

# Configuración de Notificaciones
notifications:
  enabled: false
  email_enabled: false
  webhook_enabled: false
  
  # Configuración de email
  email:
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    username: ""
    password: ""
    from_address: ""
    to_addresses: []
  
  # Configuración de webhook
  webhook:
    url: ""
    method: "POST"
    headers: {}
    timeout: 10

# Configuración de Integración
integration:
  nuclei:
    enabled: true
    template_path: "./nuclei-templates/"
    custom_templates: true
    severity_filter: ["high", "critical"]
  
  nmap:
    enabled: true
    service_detection: true
    version_detection: true
  
  cve_scan:
    enabled: true
    api_key: ""
    max_results: 50

# Configuración de Desarrollo
development:
  debug_requests: false
  save_raw_responses: false
  mock_external_tools: false
  test_mode: false
  
  # Configuración de testing
  test_urls:
    - "https://httpbin.org/html"
    - "https://example.com"
    - "https://wordpress.org"
  
  # Configuración de mock
  mock_responses:
    wappalyzer: "./test_data/mock_wappalyzer.json"
    whatweb: "./test_data/mock_whatweb.txt"
    httpx: "./test_data/mock_httpx.json"

# Configuración de Límites
limits:
  max_url_length: 2048
  max_response_size: "10MB"
  max_technologies_per_url: 100
  max_concurrent_requests: 10
  max_detection_time: 300  # 5 minutos

# Configuración de Filtros
filters:
  # Tecnologías a ignorar
  ignore_technologies:
    - "Google Analytics"
    - "Google Tag Manager"
  
  # Dominios a ignorar
  ignore_domains:
    - "localhost"
    - "127.0.0.1"
  
  # Extensiones de archivo a ignorar
  ignore_extensions:
    - ".jpg"
    - ".png"
    - ".gif"
    - ".css"
    - ".js"
    - ".ico"

# Configuración de Proxy
proxy:
  enabled: false
  http_proxy: ""
  https_proxy: ""
  no_proxy: ["localhost", "127.0.0.1"]
  auth_enabled: false
  username: ""
  password: ""

# Configuración de User-Agent
user_agent:
  default: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
  rotate: true
  custom_agents:
    - "PentestExpress/1.0 Security Scanner"
    - "Mozilla/5.0 (compatible; SecurityBot/1.0)"

# Configuración de SSL/TLS
ssl:
  verify_certificates: true
  allow_self_signed: false
  custom_ca_bundle: ""
  min_tls_version: "1.2"

# Configuración de Actualización
update:
  auto_update_enabled: false
  check_interval: 86400  # 24 horas
  update_sources:
    - "https://api.github.com/repos/wappalyzer/wappalyzer"
    - "https://api.github.com/repos/urbanadventurer/whatweb"
  
  # Configuración de backup antes de actualizar
  backup_before_update: true
  backup_path: "./backups/"

# Configuración de Plugins
plugins:
  enabled: false
  plugin_directory: "./plugins/"
  auto_load: true
  
  # Plugins disponibles
  available_plugins:
    - "custom_fingerprints"
    - "advanced_analysis"
    - "custom_reports"

# Configuración de API
api:
  enabled: false
  host: "0.0.0.0"
  port: 8080
  auth_required: true
  api_key: ""
  rate_limit: 100  # requests per minute
  cors_enabled: true
  cors_origins: ["*"]

# Configuración de Base de Datos
database:
  enabled: false
  type: "sqlite"  # sqlite, postgresql, mysql
  host: "localhost"
  port: 5432
  database: "pentest_express"
  username: ""
  password: ""
  
  # Configuración de SQLite
  sqlite_path: "./data/enhanced_detection.db"
  
  # Configuración de conexión
  pool_size: 5
  max_overflow: 10
  pool_timeout: 30